"""Train Studio — training script generation + subprocess manager"""
import os
import re
import signal
import subprocess
import sys
import time
from datetime import datetime

from .config import TrainingConfig

PYTHON = os.environ.get("PYTHON") or sys.executable


def generate_train_script(cfg: TrainingConfig) -> str:
    """Generate a parameterized training script (adapted from proven train_ornith_fable.py)."""
    modules = ", ".join(f'"{m}"' for m in cfg.target_list())
    # per-GPU VRAM (GiB) — custom or auto 9GiB
    n_gpus = len(cfg.gpus)
    mems = cfg.vram_list(n_gpus)
    if mems:
        max_memory_expr = "{" + ", ".join(f'{i}: "{m:g}GiB"' for i, m in enumerate(mems)) + "}"
    else:
        max_memory_expr = "{" + ", ".join(f'{i}: "9GiB"' for i in range(n_gpus)) + "}"
    max_steps_line = f"max_steps={cfg.max_steps}," if cfg.max_steps and cfg.max_steps > 0 else ""
    return f'''#!/usr/bin/env python3
"""Auto-generated by Train Studio — {cfg.job_name}"""
import os, sys, json, torch, logging, resource, glob

resource.setrlimit(resource.RLIMIT_NOFILE, (65536, 65536))
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
os.environ["CUDA_VISIBLE_DEVICES"] = "{','.join(map(str, cfg.gpus))}"

import unsloth
from unsloth import FastLanguageModel
from datasets import load_dataset
from torch.utils.data import Dataset
from transformers import TrainingArguments, Trainer, TrainerCallback

logging.basicConfig(level=logging.INFO, format="%(message)s", stream=sys.stdout, force=True)
log = logging.getLogger("train")

MODEL = r"{cfg.model}"
DATA_DIR = r"{cfg.dataset}"
MAX_SEQ = {cfg.max_seq}
LR = {cfg.lr}
EPOCHS = {cfg.epochs}
BATCH = {cfg.batch}
GA = {cfg.grad_accum}
SAVE_EVERY = {cfg.save_every}
OUT = r"{cfg.output_dir}/{cfg.job_name}"
NUM_WORKERS = 8

# ── Model ──
log.info("Loading model...")
model, tokenizer = FastLanguageModel.from_pretrained(
    MODEL, max_seq_length=MAX_SEQ,
    dtype=torch.bfloat16 if {cfg.bf16} else (torch.float16 if {cfg.fp16} else torch.bfloat16),
    load_in_4bit={cfg.load_in_4bit}, trust_remote_code=True,
    device_map="auto", max_memory={max_memory_expr},
)

# Freeze vision tower (text-only SFT, multimodal models)
n_frozen = 0
for n, p in model.named_parameters():
    if n.startswith("model.visual"):
        p.requires_grad = False
        n_frozen += 1
log.info(f"Frozen vision params: {{n_frozen}}")

model = FastLanguageModel.get_peft_model(
    model, r={cfg.lora_r}, lora_alpha={cfg.lora_alpha}, lora_dropout={cfg.lora_dropout},
    target_modules=[{modules}],
    use_gradient_checkpointing="unsloth", random_state=42,
)
model.print_trainable_parameters()

# ── Dataset ──
log.info("Loading dataset...")
train_raw = load_dataset("json", data_files=os.path.join(DATA_DIR, "{cfg.train_file}"), split="train")
val_raw = load_dataset("json", data_files=os.path.join(DATA_DIR, "{cfg.val_file}"), split="train")
log.info(f"Train: {{len(train_raw)}} | Val: {{len(val_raw)}}")

sft_tok = tokenizer.tokenizer if hasattr(tokenizer, "tokenizer") else tokenizer
if sft_tok.pad_token is None:
    sft_tok.pad_token = sft_tok.eos_token

# ── Sequential tokenization (tokenizer not thread-safe) ──
asst_ids = sft_tok.encode("<|im_start|>assistant", add_special_tokens=False)
asst_tensor = torch.tensor(asst_ids, dtype=torch.long)

def tokenize_all(data, name="train"):
    samples = []
    n = len(data)
    log.info(f"  Tokenizing {{name}} ({{n}} samples)...")
    for i, row in enumerate(data):
        text = row["text"]
        if not text: continue
        enc = sft_tok(text, truncation=True, max_length=MAX_SEQ, return_tensors="pt")
        ids = enc["input_ids"][0].to(dtype=torch.long)
        mask = enc["attention_mask"][0]
        labels = ids.clone()
        for j in range(len(ids) - len(asst_ids) + 1):
            if (ids[j:j+len(asst_ids)] == asst_tensor).all():
                labels[:j] = -100
                break
        samples.append({{"input_ids": ids, "labels": labels, "attention_mask": mask}})
        if i > 0 and i % 2000 == 0:
            log.info(f"    {{i}}/{{n}} ({{100*i//n}}%)")
    log.info(f"  {{name}}: {{len(samples)}} samples")
    return samples

log.info("Tokenizing...")
train_samples = tokenize_all(train_raw, "train")
del train_raw
val_samples = tokenize_all(val_raw, "val")
del val_raw

import gc; gc.collect()

class SFTDataset(Dataset):
    def __init__(self, samples): self.samples = samples
    def __len__(self): return len(self.samples)
    def __getitem__(self, i): return self.samples[i]

train_ds, val_ds = SFTDataset(train_samples), SFTDataset(val_samples)

class Collator:
    def __init__(self, pad_id=0): self.pad_id = pad_id
    def __call__(self, batch):
        ids = [s["input_ids"] for s in batch]
        labs = [s["labels"] for s in batch]
        masks = [s["attention_mask"] for s in batch]
        mlen = max(len(i) for i in ids)
        pad = torch.full((len(batch), mlen), self.pad_id, dtype=torch.long)
        plab = torch.full((len(batch), mlen), -100, dtype=torch.long)
        pmask = torch.zeros((len(batch), mlen), dtype=torch.long)
        for i, (id_, lab, mask) in enumerate(zip(ids, labs, masks)):
            pad[i, :len(id_)] = id_
            plab[i, :len(lab)] = lab
            pmask[i, :len(mask)] = mask
        return {{"input_ids": pad, "labels": plab, "attention_mask": pmask}}

# ── Args ──
eff = BATCH * GA
steps_per_epoch = len(train_ds) // eff
if {cfg.max_steps} > 0:
    max_steps = {cfg.max_steps}
else:
    max_steps = int(steps_per_epoch * EPOCHS)
log.info(f"Eff batch: {{eff}}, steps/epoch: ~{{steps_per_epoch}}, max_steps: {{max_steps}}")

args = TrainingArguments(
    output_dir=OUT, num_train_epochs=EPOCHS, max_steps=max_steps,
    per_device_train_batch_size=BATCH, gradient_accumulation_steps=GA,
    gradient_checkpointing=True, gradient_checkpointing_kwargs={{"use_reentrant": False}},
    learning_rate=LR, lr_scheduler_type="{cfg.scheduler}", warmup_ratio={cfg.warmup_ratio},
    weight_decay={cfg.weight_decay}, optim="{cfg.optim}", max_grad_norm=1.0, logging_steps=1,
    save_strategy="steps", save_steps=SAVE_EVERY, save_total_limit={cfg.save_total_limit},
    eval_strategy="no",
    bf16={cfg.bf16}, fp16={cfg.fp16}, dataloader_num_workers=4,
    remove_unused_columns=True, report_to="none", seed=42, logging_first_step=True)

trainer = Trainer(model=model, args=args, train_dataset=train_ds, eval_dataset=val_ds,
                  data_collator=Collator(pad_id=sft_tok.pad_token_id or 0))

class SaveCB(TrainerCallback):
    def __init__(s, e, o): s.e, s.o, s.s = e, o, []
    def on_step_end(s, a, state, c, model=None, **kw):
        if state.global_step > 0 and state.global_step % s.e == 0:
            ck = os.path.join(s.o, f"checkpoint-{{state.global_step}}")
            os.makedirs(ck, exist_ok=True)
            if model: model.save_pretrained(ck); s.s.append(state.global_step)
            if len(s.s) > 5:
                import shutil; shutil.rmtree(os.path.join(s.o, f"checkpoint-{{s.s.pop(0)}}"), ignore_errors=True)
        return c
trainer.add_callback(SaveCB(SAVE_EVERY, OUT))

resume_ckpt = None
if os.path.exists(OUT):
    ckpts = sorted(glob.glob(os.path.join(OUT, "checkpoint-*")), key=lambda x: int(x.split("-")[-1]))
    if ckpts:
        resume_ckpt = ckpts[-1]
        log.info(f"Resuming from checkpoint: {{resume_ckpt}}")

log.info("=" * 50)
log.info(f"Target: {{EPOCHS}} epochs (~{{max_steps}} steps)")
log.info("=" * 50)

trainer.train(resume_from_checkpoint=resume_ckpt)

os.makedirs(f"{{OUT}}/final", exist_ok=True)
model.save_pretrained(f"{{OUT}}/final")
sft_tok.save_pretrained(f"{{OUT}}/final")
with open(f"{{OUT}}/training_config.json", "w") as f:
    json.dump({{"base_model": MODEL, "lora_r": {cfg.lora_r}, "lora_alpha": {cfg.lora_alpha},
               "max_seq_length": MAX_SEQ, "epochs": EPOCHS}}, f, indent=2)
log.info(f"DONE! {{OUT}}/final")
'''


def write_train_script(cfg: TrainingConfig, script_dir="/root/train-studio/scripts"):
    os.makedirs(script_dir, exist_ok=True)
    path = os.path.join(script_dir, f"{cfg.job_name}.py")
    with open(path, "w") as f:
        f.write(generate_train_script(cfg))
    return path


class TrainerManager:
    """Manages the training subprocess: start/stop/status/log."""

    def __init__(self, log_dir="/root/train-studio/logs"):
        self.log_dir = log_dir
        os.makedirs(log_dir, exist_ok=True)
        self.proc = None
        self.log_path = None
        self.cfg = None

    @property
    def running(self):
        return self.proc is not None and self.proc.poll() is None

    def start(self, cfg: TrainingConfig):
        if self.running:
            return {"error": "Training already running"}
        script = write_train_script(cfg)
        self.cfg = cfg
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.log_path = os.path.join(self.log_dir, f"{cfg.job_name}_{ts}.log")
        env = os.environ.copy()
        env["CUDA_VISIBLE_DEVICES"] = ",".join(map(str, cfg.gpus))
        if cfg.hf_token:
            env["HF_TOKEN"] = cfg.hf_token
        logf = open(self.log_path, "w")
        self.proc = subprocess.Popen(
            [PYTHON, "-u", script],
            env=env, stdout=logf, stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        return {"started": True, "pid": self.proc.pid, "log": self.log_path, "script": script}

    def stop(self):
        if self.proc and self.running:
            os.killpg(os.getpgid(self.proc.pid), signal.SIGTERM)
            time.sleep(2)
            if self.proc.poll() is None:
                os.killpg(os.getpgid(self.proc.pid), signal.SIGKILL)
            return {"stopped": True}
        return {"error": "Nothing running"}

    def tail_log(self, n=80):
        if not self.log_path or not os.path.exists(self.log_path):
            return "(no log yet)"
        with open(self.log_path, errors="replace") as f:
            lines = f.readlines()
        return "".join(lines[-n:])[-12000:]

    def progress(self):
        """Parse log -> {step, total, loss, lr, epoch, eta}"""
        if not self.log_path or not os.path.exists(self.log_path):
            return {"status": "idle"}
        if self.running:
            status = "running"
        elif self.proc is not None and self.proc.returncode == 0:
            status = "done"
        elif self.proc is not None:
            status = "exited"
        else:
            status = "idle"
        data = {"status": status}
        try:
            with open(self.log_path, errors="replace") as f:
                text = f.read()
            m = re.findall(r"(\d+)/(\d+)\s*\[", text)
            if m:
                data["step"], data["total"] = int(m[-1][0]), int(m[-1][1])
            m = re.findall(r"'loss':\s*'([0-9.]+)'", text)
            if m:
                data["loss"] = float(m[-1])
            m = re.findall(r"'learning_rate':\s*'([0-9.eE+-]+)'", text)
            if m:
                data["lr"] = float(m[-1])
            m = re.findall(r"Resuming from checkpoint: (\S+)", text)
            if m:
                data["resume"] = m[-1]
            if "DONE!" in text:
                data["status"] = "done"
            m = re.findall(r"Error|Traceback|OutOfMemory", text)
            if m and status != "done":
                data["error"] = m[-1]
        except Exception:
            pass
        return data
